// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bdiv_braycurtis_w
NumericVector bdiv_braycurtis_w(NumericVector counts, int n_otus, IntegerVector pairs, int n_pairs, int nThreads);
RcppExport SEXP _rbiom_bdiv_braycurtis_w(SEXP countsSEXP, SEXP n_otusSEXP, SEXP pairsSEXP, SEXP n_pairsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_otus(n_otusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdiv_braycurtis_w(counts, n_otus, pairs, n_pairs, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// bdiv_braycurtis_u
NumericVector bdiv_braycurtis_u(NumericVector counts, int n_otus, IntegerVector pairs, int n_pairs, int nThreads);
RcppExport SEXP _rbiom_bdiv_braycurtis_u(SEXP countsSEXP, SEXP n_otusSEXP, SEXP pairsSEXP, SEXP n_pairsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_otus(n_otusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdiv_braycurtis_u(counts, n_otus, pairs, n_pairs, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// bdiv_euclidean_w
NumericVector bdiv_euclidean_w(NumericVector counts, int n_otus, IntegerVector pairs, int n_pairs, int nThreads);
RcppExport SEXP _rbiom_bdiv_euclidean_w(SEXP countsSEXP, SEXP n_otusSEXP, SEXP pairsSEXP, SEXP n_pairsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_otus(n_otusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdiv_euclidean_w(counts, n_otus, pairs, n_pairs, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// bdiv_euclidean_u
NumericVector bdiv_euclidean_u(NumericVector counts, int n_otus, IntegerVector pairs, int n_pairs, int nThreads);
RcppExport SEXP _rbiom_bdiv_euclidean_u(SEXP countsSEXP, SEXP n_otusSEXP, SEXP pairsSEXP, SEXP n_pairsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_otus(n_otusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdiv_euclidean_u(counts, n_otus, pairs, n_pairs, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// bdiv_manhattan_w
NumericVector bdiv_manhattan_w(NumericVector counts, int n_otus, IntegerVector pairs, int n_pairs, int nThreads);
RcppExport SEXP _rbiom_bdiv_manhattan_w(SEXP countsSEXP, SEXP n_otusSEXP, SEXP pairsSEXP, SEXP n_pairsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_otus(n_otusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdiv_manhattan_w(counts, n_otus, pairs, n_pairs, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// bdiv_manhattan_u
NumericVector bdiv_manhattan_u(NumericVector counts, int n_otus, IntegerVector pairs, int n_pairs, int nThreads);
RcppExport SEXP _rbiom_bdiv_manhattan_u(SEXP countsSEXP, SEXP n_otusSEXP, SEXP pairsSEXP, SEXP n_pairsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_otus(n_otusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdiv_manhattan_u(counts, n_otus, pairs, n_pairs, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// bdiv_jaccard_w
NumericVector bdiv_jaccard_w(NumericVector counts, int n_otus, IntegerVector pairs, int n_pairs, int nThreads);
RcppExport SEXP _rbiom_bdiv_jaccard_w(SEXP countsSEXP, SEXP n_otusSEXP, SEXP pairsSEXP, SEXP n_pairsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_otus(n_otusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdiv_jaccard_w(counts, n_otus, pairs, n_pairs, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// bdiv_jaccard_u
NumericVector bdiv_jaccard_u(NumericVector counts, int n_otus, IntegerVector pairs, int n_pairs, int nThreads);
RcppExport SEXP _rbiom_bdiv_jaccard_u(SEXP countsSEXP, SEXP n_otusSEXP, SEXP pairsSEXP, SEXP n_pairsSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_otus(n_otusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bdiv_jaccard_u(counts, n_otus, pairs, n_pairs, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// parallel_unifrac
NumericVector parallel_unifrac(List sparseMatrix, IntegerMatrix pairs, List tree, bool weighted, int nThreads);
RcppExport SEXP _rbiom_parallel_unifrac(SEXP sparseMatrixSEXP, SEXP pairsSEXP, SEXP treeSEXP, SEXP weightedSEXP, SEXP nThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sparseMatrix(sparseMatrixSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< List >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    Rcpp::traits::input_parameter< int >::type nThreads(nThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_unifrac(sparseMatrix, pairs, tree, weighted, nThreads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_alpha_div
List rcpp_alpha_div(List sparseMatrix);
RcppExport SEXP _rbiom_rcpp_alpha_div(SEXP sparseMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sparseMatrix(sparseMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_alpha_div(sparseMatrix));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rarefy
List rcpp_rarefy(List sparseMatrix, int depth, int seed);
RcppExport SEXP _rbiom_rcpp_rarefy(SEXP sparseMatrixSEXP, SEXP depthSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type sparseMatrix(sparseMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rarefy(sparseMatrix, depth, seed));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_read_tree
List rcpp_read_tree(const char* tree);
RcppExport SEXP _rbiom_rcpp_read_tree(SEXP treeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type tree(treeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_read_tree(tree));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rbiom_bdiv_braycurtis_w", (DL_FUNC) &_rbiom_bdiv_braycurtis_w, 5},
    {"_rbiom_bdiv_braycurtis_u", (DL_FUNC) &_rbiom_bdiv_braycurtis_u, 5},
    {"_rbiom_bdiv_euclidean_w", (DL_FUNC) &_rbiom_bdiv_euclidean_w, 5},
    {"_rbiom_bdiv_euclidean_u", (DL_FUNC) &_rbiom_bdiv_euclidean_u, 5},
    {"_rbiom_bdiv_manhattan_w", (DL_FUNC) &_rbiom_bdiv_manhattan_w, 5},
    {"_rbiom_bdiv_manhattan_u", (DL_FUNC) &_rbiom_bdiv_manhattan_u, 5},
    {"_rbiom_bdiv_jaccard_w", (DL_FUNC) &_rbiom_bdiv_jaccard_w, 5},
    {"_rbiom_bdiv_jaccard_u", (DL_FUNC) &_rbiom_bdiv_jaccard_u, 5},
    {"_rbiom_parallel_unifrac", (DL_FUNC) &_rbiom_parallel_unifrac, 5},
    {"_rbiom_rcpp_alpha_div", (DL_FUNC) &_rbiom_rcpp_alpha_div, 1},
    {"_rbiom_rcpp_rarefy", (DL_FUNC) &_rbiom_rcpp_rarefy, 3},
    {"_rbiom_rcpp_read_tree", (DL_FUNC) &_rbiom_rcpp_read_tree, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rbiom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
