#' Estimate the diversity of each sample.
#' 
#' @name adiv_table
#' 
#' @param biom  A \code{matrix}, \code{simple_triplet_matrix}, or \code{BIOM}
#'        object, as returned from \link{read_biom}. For matrices, the rows and
#'        columns are assumed to be the taxa and samples, respectively.
#'     
#' @param rarefy  Control how/whether rarefactions are done prior to alpha 
#'        diversity computations. Options are: 
#'        \describe{
#'        
#'          \item{\code{FALSE}}{
#'            Use each sample's current set of observations without applying
#'            any rarefaction. (Default) }
#'            
#'          \item{\code{TRUE}}{
#'            Automatically select and apply a single rarefaction. }
#'            
#'          \item{\code{"multi"}, \code{"multi_log"}, \code{"multi_even"}}{
#'            Automatically select and apply multiple rarefactions.
#'            \code{"multi"} provides \code{"multi_log"} at the low end 
#'            and \code{"multi_even"} at the high end. }
#'            
#'          \item{\emph{integer vector}}{
#'            Rarefy at the specified depth(s). }
#'        }
#'     
#' @param metrics  Character vector of one or more of the following: 
#'        \code{Depth}, \code{OTUs}, \code{Shannon}, \code{Chao1}, 
#'        \code{Simpson}, \code{InvSimpson}. Non-ambiguous abbreviations are 
#'        also accepted. The default, \code{all}, returns all of them.
#'     
#' @param long  Pivot the returned data to long format?
#'        \describe{
#'          \item{\bold{FALSE}}{ Each metric has its own column. (Default) }
#'          \item{\bold{TRUE}}{
#'            "Sample", "Metric" and "Diversity" are the columns returned. Rows
#'            are added to attain all combinations of samples x metrics. }
#'        }
#'     
#' @param md  Include metadata in the output data frame? Options are: 
#'     \describe{
#'       \item{\code{FALSE}}{ Don't include metadata. (Default) }
#'       \item{\code{TRUE}}{ Include all metadata. }
#'       \item{\emph{character vector}}{
#'         Include only the specified metadata columns. }
#'     }
#'        
#' @param safe  Should autogenerated columns be prefixed with a "." to avoid 
#'        conflicting with metadata column names? (Default: FALSE)
#'        
#' @return A data frame of four diversity values for each sample in
#'         \code{biom}. The column names are \bold{Sample}, \bold{Depth} and 
#'         the diversity metrics: \bold{OTUs}, \bold{Shannon}, \bold{Chao1}, 
#'         \bold{Simpson}, and \bold{InvSimpson}. The row names are the sample 
#'         names, except when multiple rarefactions are done.
#'     
#' @export
#' @examples
#'     library(rbiom)
#'     
#'     ad <- adiv_table(hmp50)
#'     head(ad)
#'     
#'     biom <- subset(hmp50, `Body Site` == "Saliva" & Age < 26)
#'     ad   <- adiv_table(biom, "multi")
#'     boxplot(Shannon ~ Depth, data=ad, xlab="Reads", ylab="Diversity")
#'     


adiv_table <- function (biom, rarefy=FALSE, metrics="all", long=FALSE, md=FALSE, safe=FALSE) {
  
  with_cache("adiv_table", environment(), NULL, local({
    
    
    #________________________________________________________
    # Enable abbreviations of metric names.
    #________________________________________________________
    if (!identical(metrics, 'all')) {
      metricList <- c("Depth", "OTUs", "Shannon", "Chao1", "Simpson", "InvSimpson")
      metrics    <- metricList[pmatch(tolower(metrics), tolower(metricList))]
      metrics    <- metrics[!is.na(metrics)]
      if (length(metrics) == 0) stop(simpleError("Invalid 'adiv_table(metric=' argument"))
    }
    
    
    #________________________________________________________
    # Get the input into a simple_triplet_matrix
    #________________________________________________________
    if (is(biom, "simple_triplet_matrix")) { counts <- biom
    } else if (is(biom, "BIOM"))           { counts <- biom$counts
    } else if (is(biom, "matrix"))         { counts <- slam::as.simple_triplet_matrix(biom)
    } else {
      stop(simpleError("biom must be a matrix, simple_triplet_matrix, or BIOM object."))
    }
    
    
    #________________________________________________________
    # Define the rarefaction depths to sample at
    #________________________________________________________
    rLvls <- NA
    
    if (identical(rarefy, TRUE)) {
      counts <- rarefy(counts)
      
    } else if (is.numeric(rarefy)) {
      rLvls <- sort(rarefy)
      
    } else if (is.character(rarefy)) {
      upper <- fivenum(slam::col_sums(counts))[[4]]
      
      if (identical(rarefy, "multi")) {
        
        # Log intervals until rLvl/2, then even intervals until rLvl*2
        rLvl  <- default_rarefaction_depth(counts)
        rLvls <- 10 ** (c(1,3,5,7,8,9) * (log10(rLvl / 2) / 10))
        rLvls <- c(rLvls, seq(from = rLvl / 2, to = rLvl * 2, length.out = 5))
        rLvls <- floor(rLvls)
        remove("rLvl")
        
      } else if (identical(rarefy, "multi_log")) {
        rLvls <- floor(10 ** (c(1:10) * (log10(upper) / 10)))
        
      } else if (identical(rarefy, "multi_even")) {
        rLvls <- floor(seq(from = 5, to = upper, length.out = 10))
      }
      remove("upper")
    }
    
    
    result <- NULL
    
    for (rLvl in rLvls) {
      
      otus <- if (is.na(rLvl)) counts else rarefy(counts, rLvl)
      df   <- rcpp_alpha_div(otus)
      
      
      #________________________________________________________
      # Convert 'all' to actual names of all adiv metrics
      #________________________________________________________
      if ('all' %in%  metrics)
        metrics <- colnames(df)[-1]
      
      
      #________________________________________________________
      # Pivot Longer
      #________________________________________________________
      if (isTRUE(long)) {
        
          mtx <- as.matrix(df[,metrics,drop=F])
          df  <- data.frame(
            stringsAsFactors = FALSE,
            Sample    = df[['Sample']][row(mtx)],
            Depth     = df[['Depth']][row(mtx)],
            Metric    = colnames(mtx)[col(mtx)],
            Diversity = as.numeric(mtx)
          )
        
      } else {
        
        #________________________________________________________
        # The metrics of interest in wide format
        #________________________________________________________
        if (length(rLvls) == 1) {
          df <- df[,c('Sample', metrics),drop=F]
        } else {
          df <- df[,unique(c('Sample', 'Depth', metrics)),drop=F]
        }
      }
      
      
      
      result <- rbind(result, df)
      
    }
    
    
    #________________________________________________________
    # Add rownames and facet attribute when appropriate
    #________________________________________________________
    if (length(rLvls) == 1 && !isTRUE(long))
      rownames(result) <- result[['Sample']]
    
    if (isTRUE(long)) {
      result[['Metric']] %<>% factor(levels = metrics)
      if (length(metrics) > 1)
        attr(result, 'facet') <- ifelse(safe, '.metric', 'Metric')
    }
    
    
    #________________________________________________________
    # Make the auto-generated columns safe
    #________________________________________________________
    if (isTRUE(safe)) {
      colnames(result) <- paste0(".", tolower(colnames(result)))
      colnames(result) <- sub(".diversity", ".value", colnames(result))
    }
    
    
    
    #________________________________________________________
    # Add Metadata
    #________________________________________________________
    if (identical(md, TRUE))  md <- colnames(metadata(biom))
    if (identical(md, FALSE)) md <- c()
    for (i in unique(md))
      result[[i]] <- metadata(biom, i)[result[[1]]]
    
    
    return (result)
  
  }))
}
