# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

par_beta_div <- function(counts, pairs, bdiv, weighted) {
    .Call(`_rbiom_par_beta_div`, counts, pairs, bdiv, weighted)
}

par_unifrac <- function(sparseMatrix, pairs, tree, weighted) {
    .Call(`_rbiom_par_unifrac`, sparseMatrix, pairs, tree, weighted)
}

rcpp_alpha_div <- function(sparseMatrix) {
    .Call(`_rbiom_rcpp_alpha_div`, sparseMatrix)
}

rcpp_rarefy <- function(sparseMatrix, depth, seed = 0L) {
    .Call(`_rbiom_rcpp_rarefy`, sparseMatrix, depth, seed)
}

rcpp_read_tree <- function(tree) {
    .Call(`_rbiom_rcpp_read_tree`, tree)
}

