# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bdiv_braycurtis_w <- function(counts, n_otus, pairs, n_pairs, nThreads) {
    .Call(`_rbiom_bdiv_braycurtis_w`, counts, n_otus, pairs, n_pairs, nThreads)
}

bdiv_braycurtis_u <- function(counts, n_otus, pairs, n_pairs, nThreads) {
    .Call(`_rbiom_bdiv_braycurtis_u`, counts, n_otus, pairs, n_pairs, nThreads)
}

bdiv_euclidean_w <- function(counts, n_otus, pairs, n_pairs, nThreads) {
    .Call(`_rbiom_bdiv_euclidean_w`, counts, n_otus, pairs, n_pairs, nThreads)
}

bdiv_euclidean_u <- function(counts, n_otus, pairs, n_pairs, nThreads) {
    .Call(`_rbiom_bdiv_euclidean_u`, counts, n_otus, pairs, n_pairs, nThreads)
}

bdiv_manhattan_w <- function(counts, n_otus, pairs, n_pairs, nThreads) {
    .Call(`_rbiom_bdiv_manhattan_w`, counts, n_otus, pairs, n_pairs, nThreads)
}

bdiv_manhattan_u <- function(counts, n_otus, pairs, n_pairs, nThreads) {
    .Call(`_rbiom_bdiv_manhattan_u`, counts, n_otus, pairs, n_pairs, nThreads)
}

bdiv_jaccard_w <- function(counts, n_otus, pairs, n_pairs, nThreads) {
    .Call(`_rbiom_bdiv_jaccard_w`, counts, n_otus, pairs, n_pairs, nThreads)
}

bdiv_jaccard_u <- function(counts, n_otus, pairs, n_pairs, nThreads) {
    .Call(`_rbiom_bdiv_jaccard_u`, counts, n_otus, pairs, n_pairs, nThreads)
}

parallel_unifrac <- function(sparseMatrix, pairs, tree, weighted, nThreads) {
    .Call(`_rbiom_parallel_unifrac`, sparseMatrix, pairs, tree, weighted, nThreads)
}

rcpp_alpha_div <- function(sparseMatrix) {
    .Call(`_rbiom_rcpp_alpha_div`, sparseMatrix)
}

rcpp_rarefy <- function(sparseMatrix, depth, seed = 0L) {
    .Call(`_rbiom_rcpp_rarefy`, sparseMatrix, depth, seed)
}

rcpp_read_tree <- function(tree) {
    .Call(`_rbiom_rcpp_read_tree`, tree)
}

