# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

par_unifrac <- function(sparseMatrix, tree, weighted) {
    .Call(`_rbiom_par_unifrac`, sparseMatrix, tree, weighted)
}

rcpp_distance <- function(iJob, nJobs, sparseMatrix, method, weighted) {
    .Call(`_rbiom_rcpp_distance`, iJob, nJobs, sparseMatrix, method, weighted)
}

rcpp_read_tree <- function(tree) {
    .Call(`_rbiom_rcpp_read_tree`, tree)
}

rcpp_unifrac <- function(iJob, nJobs, sparseMatrix, tree, weighted) {
    .Call(`_rbiom_rcpp_unifrac`, iJob, nJobs, sparseMatrix, tree, weighted)
}

